wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718440467.0
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 100
      2:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 100
      3:
      - 13
      - 23
      4: 3.11.0
      5: 0.16.6
      6: 4.39.3
      8:
      - 4
      - 5
      13: darwin-arm64
dataset_name:
  desc: null
  value: glue
dataset_task:
  desc: null
  value: mrpc
num_classes:
  desc: null
  value: 2
dataset_size:
  desc: null
  value: 971
test_dataset_size:
  desc: null
  value: 484
validation_dataset_size:
  desc: null
  value: 483
train_dataset_size:
  desc: null
  value: 4
seed_num:
  desc: null
  value: 1
range_to_select:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 5.0e-05
model_name:
  desc: null
  value: distilbert-base-uncased
device:
  desc: null
  value: cpu
model_type:
  desc: null
  value: bert
optimizer:
  desc: null
  value: fosi
criterion:
  desc: null
  value: cross_entropy
task_type:
  desc: null
  value: classification
mode:
  desc: null
  value: training
eval_steps:
  desc: null
  value: 2
