wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715180780.0
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 35
      - 49
      - 51
      - 53
      - 55
      - 100
      2:
      - 1
      - 5
      - 11
      - 12
      - 35
      - 49
      - 51
      - 53
      - 55
      - 100
      3:
      - 2
      - 13
      - 23
      - 61
      4: 3.11.0
      5: 0.16.6
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
dataset_name:
  desc: null
  value: glue
dataset_task:
  desc: null
  value: cola
num_classes:
  desc: null
  value: 2
dataset_size:
  desc: null
  value: 9594
test_dataset_size:
  desc: null
  value: 800
validation_dataset_size:
  desc: null
  value: 799
train_dataset_size:
  desc: null
  value: 7995
k_approx:
  desc: null
  value: 10
seed_num:
  desc: null
  value: 1000
range_to_select:
  desc: null
  value: null
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 10
num_of_optimizer_iterations:
  desc: null
  value: 190
learning_rate:
  desc: null
  value: 2.297635639830886e-05
model_name:
  desc: null
  value: distilbert-base-uncased
device:
  desc: null
  value: cpu
model_type:
  desc: null
  value: bert
optimizer:
  desc: null
  value: fosi
criterion:
  desc: null
  value: cross_entropy
task_type:
  desc: null
  value: classification
eval_steps:
  desc: null
  value: 500
logging_steps:
  desc: null
  value: 500
